name: emergency_app_flutter
description: A minimal emergency preparedness app.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_map: ^6.0.0
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  provider: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.2.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_animate: ^4.4.1
  flutter_staggered_animations: ^1.1.1
dev_dependencies:
  hive_generator: ^1.1.0
  build_runner: ^2.4.6

flutter:
    uses-material-design: true
    generate: true